# Generated by Django 3.0.3 on 2020-11-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='analytics_users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=25)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('videoid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('users_watched_count', models.IntegerField(default=0)),
                ('embed_code', models.TextField()),
                ('viewed_by_users', models.TextField()),
            ],
        ),
    ]
