# Generated by Django 3.0.3 on 2020-11-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video_analytics_app', '0002_auto_20201110_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='viewed_by_users',
            field=models.TextField(blank=''),
        ),
    ]
